<?php

use Illuminate\Database\Seeder;

class AreasTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $areas = [
        	[
        		'island' => [
					'name' => 'Jawa',
					'code' => '30',
	        		'provinces' => [
	        			[
							'name' => 'Banten',
							'code' => '36',
	        				'abbreviation' => 'Banten',
	        				'regencies' => [
	        					[
									'name' => 'Kabupaten Pandeglang',
									'code' => '36.01',
		        					'abbreviation' => 'PDG',
									'license_plate' => 'A',
	        					],
	        					[
		        					'name' => 'Kabupaten Lebak',
									'code' => '36.02',
		        					'abbreviation' => 'RKB',
									'license_plate' => 'A',
	        					],
	        					[
		        					'name' => 'Kabupaten Tangerang',
									'code' => '36.03',
		        					'abbreviation' => 'TGR',
									'license_plate' => 'A',
	        					],
	        					[
		        					'name' => 'Kabupaten Serang',
									'code' => '36.04',
		        					'abbreviation' => 'SRG',
									'license_plate' => 'A',
	        					],
	        					[
		        					'name' => 'Kota Tangerang',
									'code' => '36.71',
		        					'abbreviation' => 'TNG',
									'license_plate' => 'B',
	        					],
	        					[
		        					'name' => 'Kota Cilegon',
									'code' => '36.72',
		        					'abbreviation' => 'CLG',
									'license_plate' => 'A',
	        					],
	        					[
		        					'name' => 'Kota Serang',
									'code' => '36.73',
		        					'abbreviation' => 'SRG',
									'license_plate' => 'A',
	        					],
	        					[
		        					'name' => 'Kota Tangerang Selatan',
									'code' => '36.74',
		        					'abbreviation' => 'CPT',
									'license_plate' => 'B',
	        					],
	        				],
	        			],
	        			[
							'name' => 'DKI Jakarta',
							'code' => '31',
	        				'abbreviation' => 'JKT',
	        				'regencies' => [
	        					[
									'name' => 'Kabupaten Kepulauan Seribu',
									'code' => '31.01',
		        					'abbreviation' => 'KSU',
									'license_plate' => 'B',
	        					],
	        					[
		        					'name' => 'Kota Jakarta Selatan',
									'code' => '31.74',
		        					'abbreviation' => 'KYB',
									'license_plate' => 'B',
	        					],
	        					[
		        					'name' => 'Kota Jakarta Timur',
									'code' => '31.75',
		        					'abbreviation' => 'CKG',
									'license_plate' => 'B',
	        					],
	        					[
		        					'name' => 'Kota Jakarta Pusat',
									'code' => '31.71',
		        					'abbreviation' => 'TNA',
									'license_plate' => 'B',
	        					],
	        					[
		        					'name' => 'Kota Jakarta Barat',
									'code' => '31.73',
		        					'abbreviation' => 'GGP',
									'license_plate' => 'B',
	        					],
	        					[
		        					'name' => 'Kota Jakarta Utara',
									'code' => '31.72',
		        					'abbreviation' => 'TJP',
									'license_plate' => 'B',
	        					],
	        				],
	        			],
	        			[
							'name' => 'Jawa Barat',
							'code' => '32',
	        				'abbreviation' => 'Jabar',
	        				'regencies' => [
	        					[
									'name' => 'Kabupaten Bogor',
									'code' => '32.01',
		        					'abbreviation' => 'CBI',
									'license_plate' => 'F',
	        					],
	        					[
		        					'name' => 'Kabupaten Sukabumi',
									'code' => '32.02',
		        					'abbreviation' => 'SBM',
									'license_plate' => 'F',
	        					],
	        					[
		        					'name' => 'Kabupaten Cianjur',
									'code' => '32.03',
		        					'abbreviation' => 'CJR',
									'license_plate' => 'F',
	        					],
	        					[
		        					'name' => 'Kabupaten Bandung',
									'code' => '32.04',
		        					'abbreviation' => 'SOR',
									'license_plate' => 'D',
	        					],
	        					[
		        					'name' => 'Kabupaten Garut',
									'code' => '32.05',
		        					'abbreviation' => 'GRT',
									'license_plate' => 'Z',
	        					],
	        					[
		        					'name' => 'Kabupaten Tasikmalaya',
									'code' => '32.06',
		        					'abbreviation' => 'SPA',
									'license_plate' => 'Z',
	        					],
	        					[
		        					'name' => 'Kabupaten Ciamis',
									'code' => '32.07',
		        					'abbreviation' => 'CMS',
									'license_plate' => 'Z',
	        					],
	        					[
		        					'name' => 'Kabupaten Kuningan',
									'code' => '32.08',
		        					'abbreviation' => 'KNG',
									'license_plate' => 'E',
	        					],
	        					[
		        					'name' => 'Kabupaten Cirebon',
									'code' => '32.09',
		        					'abbreviation' => 'SBR',
									'license_plate' => 'E',
	        					],
	        					[
		        					'name' => 'Kabupaten Majalengka',
									'code' => '32.10',
		        					'abbreviation' => 'MJL',
									'license_plate' => 'E',
	        					],
	        					[
		        					'name' => 'Kabupaten Sumedang',
									'code' => '32.11',
		        					'abbreviation' => 'SMD',
									'license_plate' => 'Z',
	        					],
	        					[
		        					'name' => 'Kabupaten Indramayu',
									'code' => '32.12',
		        					'abbreviation' => 'IDM',
									'license_plate' => 'E',
	        					],
	        					[
		        					'name' => 'Kabupaten Subang',
									'code' => '32.13',
		        					'abbreviation' => 'SNG',
									'license_plate' => 'T',
	        					],
	        					[
		        					'name' => 'Kabupaten Purwakarta',
									'code' => '32.14',
		        					'abbreviation' => 'PWK',
									'license_plate' => 'T',
	        					],
	        					[
		        					'name' => 'Kabupaten Karawang',
									'code' => '32.15',
		        					'abbreviation' => 'KWG',
									'license_plate' => 'T',
	        					],
	        					[
		        					'name' => 'Kabupaten Bekasi',
									'code' => '32.16',
		        					'abbreviation' => 'CKR',
									'license_plate' => 'B',
	        					],
	        					[
		        					'name' => 'Kabupaten Bandung Barat',
									'code' => '32.17',
		        					'abbreviation' => 'NPH',
									'license_plate' => 'D',
	        					],
	        					[
		        					'name' => 'Kabupaten Pangandaran',
									'code' => '32.18',
		        					'abbreviation' => 'PRI',
									'license_plate' => 'Z',
	        					],
	        					[
		        					'name' => 'Kota Bogor',
									'code' => '32.71',
		        					'abbreviation' => 'BGR',
									'license_plate' => 'F',
	        					],
	        					[
		        					'name' => 'Kota Sukabumi',
									'code' => '32.72',
		        					'abbreviation' => 'SKB',
									'license_plate' => 'F',
	        					],
	        					[
		        					'name' => 'Kota Bandung',
									'code' => '32.73',
		        					'abbreviation' => 'BDG',
									'license_plate' => 'D',
	        					],
	        					[
		        					'name' => 'Kota Cirebon',
									'code' => '32.74',
		        					'abbreviation' => 'CBN',
									'license_plate' => 'E',
	        					],
	        					[
		        					'name' => 'Kota Bekasi',
									'code' => '32.75',
		        					'abbreviation' => 'BKS',
									'license_plate' => 'B',
	        					],
	        					[
		        					'name' => 'Kota Depok',
									'code' => '32.76',
		        					'abbreviation' => 'DPK',
									'license_plate' => 'B',
	        					],
	        					[
		        					'name' => 'Kota Cimahi',
									'code' => '32.77',
		        					'abbreviation' => 'CMH',
									'license_plate' => 'D',
	        					],
	        					[
		        					'name' => 'Kota Tasikmalaya',
									'code' => '32.78',
		        					'abbreviation' => 'TSM',
									'license_plate' => 'Z',
	        					],
	        					[
		        					'name' => 'Kota Banjar',
									'code' => '32.79',
		        					'abbreviation' => 'BJR',
									'license_plate' => 'Z',
	        					],
	        				],
	        			],
	        			[
	        				'name' => 'Jawa Tengah',
							'code' => '33',
	        				'abbreviation' => 'Jateng',
	        				'regencies' => [
	        					[
									'name' => 'Kabupaten Cilacap',
									'code' => '33.01',
		        					'abbreviation' => 'CLP',
									'license_plate' => 'R',
	        					],
	        					[
		        					'name' => 'Kabupaten Banyumas',
									'code' => '33.02',
		        					'abbreviation' => 'PWT',
									'license_plate' => 'R',
	        					],
	        					[
		        					'name' => 'Kabupaten Purbalingga',
									'code' => '33.03',
		        					'abbreviation' => 'PBG',
									'license_plate' => 'R',
	        					],
	        					[
		        					'name' => 'Kabupaten Banjarnegara',
									'code' => '33.04',
		        					'abbreviation' => 'BNR',
									'license_plate' => 'R',
	        					],
	        					[
		        					'name' => 'Kabupaten Kebumen',
									'code' => '33.05',
		        					'abbreviation' => 'KBM',
									'license_plate' => 'AA',
	        					],
	        					[
		        					'name' => 'Kabupaten Purworejo',
									'code' => '33.06',
		        					'abbreviation' => 'PWR',
									'license_plate' => 'AA',
	        					],
	        					[
		        					'name' => 'Kabupaten Wonosobo',
									'code' => '33.07',
		        					'abbreviation' => 'WSB',
									'license_plate' => 'AA',
	        					],
	        					[
		        					'name' => 'Kabupaten Magelang',
									'code' => '33.08',
		        					'abbreviation' => 'MKD',
									'license_plate' => 'AA',
	        					],
	        					[
		        					'name' => 'Kabupaten Boyolali',
									'code' => '33.09',
		        					'abbreviation' => 'BYL',
									'license_plate' => 'AD',
	        					],
	        					[
		        					'name' => 'Kabupaten Klaten',
									'code' => '33.10',
		        					'abbreviation' => 'KLN',
									'license_plate' => 'AD',
	        					],
	        					[
		        					'name' => 'Kabupaten Sukoharjo',
									'code' => '33.11',
		        					'abbreviation' => 'SKH',
									'license_plate' => 'AD',
	        					],
	        					[
		        					'name' => 'Kabupaten Wonogiri',
									'code' => '33.12',
		        					'abbreviation' => 'WNG',
									'license_plate' => 'AD',
	        					],
	        					[
		        					'name' => 'Kabupaten Karanganyar',
									'code' => '33.13',
		        					'abbreviation' => 'KRG',
									'license_plate' => 'AD',
	        					],
	        					[
		        					'name' => 'Kabupaten Sragen',
									'code' => '33.14',
		        					'abbreviation' => 'SGN',
									'license_plate' => 'AD',
	        					],
	        					[
		        					'name' => 'Kabupaten Grobogan',
									'code' => '33.15',
		        					'abbreviation' => 'PWD',
									'license_plate' => 'K',
	        					],
	        					[
		        					'name' => 'Kabupaten Blora',
									'code' => '33.16',
		        					'abbreviation' => 'BLA',
									'license_plate' => 'K',
	        					],
								[
		        					'name' => 'Kabupaten Rembang',
									'code' => '33.17',
		        					'abbreviation' => 'RBG',
									'license_plate' => 'K',
	        					],
								[
		        					'name' => 'Kabupaten Pati',
									'code' => '33.18',
		        					'abbreviation' => 'PTI',
									'license_plate' => 'K',
	        					],
								[
		        					'name' => 'Kabupaten Kudus',
									'code' => '33.19',
		        					'abbreviation' => 'KDS',
									'license_plate' => 'K',
	        					],
								[
		        					'name' => 'Kabupaten Jepara',
									'code' => '33.20',
		        					'abbreviation' => 'JPA',
									'license_plate' => 'K',
	        					],
								[
		        					'name' => 'Kabupaten Demak',
									'code' => '33.21',
		        					'abbreviation' => 'DMK',
									'license_plate' => 'H',
	        					],
								[
		        					'name' => 'Kabupaten Semarang',
									'code' => '33.22',
		        					'abbreviation' => 'UNR',
									'license_plate' => 'H',
	        					],
								[
		        					'name' => 'Kabupaten Temanggung',
									'code' => '33.23',
		        					'abbreviation' => 'TMG',
									'license_plate' => 'AA',
	        					],
								[
		        					'name' => 'Kabupaten Kendal',
									'code' => '33.24',
		        					'abbreviation' => 'KDL',
									'license_plate' => 'H',
	        					],
								[
		        					'name' => 'Kabupaten Batang',
									'code' => '33.25',
		        					'abbreviation' => 'BTG',
									'license_plate' => 'G',
	        					],
								[
		        					'name' => 'Kabupaten Pekalongan',
									'code' => '33.26',
		        					'abbreviation' => 'KJN',
									'license_plate' => 'G',
	        					],
								[
		        					'name' => 'Kabupaten Pemalang',
									'code' => '33.27',
		        					'abbreviation' => 'PML',
									'license_plate' => 'G',
	        					],
								[
		        					'name' => 'Kabupaten Tegal',
									'code' => '33.28',
		        					'abbreviation' => 'SLW',
									'license_plate' => 'G',
	        					],
								[
		        					'name' => 'Kabupaten Brebes',
									'code' => '33.29',
		        					'abbreviation' => 'BBS',
									'license_plate' => 'G',
	        					],
								[
		        					'name' => 'Kota Magelang',
									'code' => '33.71',
		        					'abbreviation' => 'MGG',
									'license_plate' => 'AA',
	        					],
								[
		        					'name' => 'Kota Surakarta',
									'code' => '33.72',
		        					'abbreviation' => 'SKT',
									'license_plate' => 'AD',
	        					],
								[
		        					'name' => 'Kota Salatiga',
									'code' => '33.73',
		        					'abbreviation' => 'SLT',
									'license_plate' => 'H',
	        					],
								[
		        					'name' => 'Kota Semarang',
									'code' => '33.74',
		        					'abbreviation' => 'SMG',
									'license_plate' => 'H',
	        					],
								[
		        					'name' => 'Kota Pekalongan',
									'code' => '33.75',
		        					'abbreviation' => 'PKL',
									'license_plate' => 'G',
	        					],
								[
		        					'name' => 'Kota Tegal',
									'code' => '33.76',
		        					'abbreviation' => 'TGL',
									'license_plate' => 'G',
	        					],
	        				],
	        			],
	        			[
	        				'name' => 'Jawa Timur',
							'code' => '35',
	        				'abbreviation' => 'Jatim',
	        				'regencies' => [
	        					[
									'name' => 'Kabupaten Pacitan',
									'code' => '35.01',
		        					'abbreviation' => 'PCT',
									'license_plate' => 'AE',
	        					],
								[
		        					'name' => 'Kabupaten Ponorogo',
									'code' => '35.02',
		        					'abbreviation' => 'PNG',
									'license_plate' => 'AE',
	        					],
								[
		        					'name' => 'Kabupaten Trenggalek',
									'code' => '35.03',
		        					'abbreviation' => 'TRK',
									'license_plate' => 'AG',
	        					],
								[
		        					'name' => 'Kabupaten Tulungagung',
									'code' => '35.04',
		        					'abbreviation' => 'TLG',
									'license_plate' => 'AG',
	        					],
								[
		        					'name' => 'Kabupaten Blitar',
									'code' => '35.05',
		        					'abbreviation' => 'KNR',
									'license_plate' => 'AG',
	        					],
								[
		        					'name' => 'Kabupaten Kediri',
									'code' => '35.06',
		        					'abbreviation' => 'KDR',
									'license_plate' => 'AG',
	        					],
								[
		        					'name' => 'Kabupaten Malang',
									'code' => '35.07',
		        					'abbreviation' => 'KPN',
									'license_plate' => 'N',
	        					],
								[
		        					'name' => 'Kabupaten Lumajang',
									'code' => '35.08',
		        					'abbreviation' => 'LMJ',
									'license_plate' => 'N',
	        					],
								[
		        					'name' => 'Kabupaten Jember',
									'code' => '35.09',
		        					'abbreviation' => 'JMR',
									'license_plate' => 'P',
	        					],
								[
		        					'name' => 'Kabupaten Banyuwangi',
									'code' => '35.10',
		        					'abbreviation' => 'BYW',
									'license_plate' => 'P',
	        					],
								[
		        					'name' => 'Kabupaten Bondowoso',
									'code' => '35.11',
		        					'abbreviation' => 'BDW',
									'license_plate' => 'P',
	        					],
								[
		        					'name' => 'Kabupaten Situbondo',
									'code' => '35.12',
		        					'abbreviation' => 'SIT',
									'license_plate' => 'P',
	        					],
								[
		        					'name' => 'Kabupaten Probolinggo',
									'code' => '35.13',
		        					'abbreviation' => 'KRS',
									'license_plate' => 'N',
	        					],
								[
		        					'name' => 'Kabupaten Pasuruan',
									'code' => '35.14',
		        					'abbreviation' => 'PSR',
									'license_plate' => 'N',
	        					],
								[
		        					'name' => 'Kabupaten Sidoarjo',
									'code' => '35.15',
		        					'abbreviation' => 'SDA',
									'license_plate' => 'W',
	        					],
								[
		        					'name' => 'Kabupaten Mojokerto',
									'code' => '35.16',
		        					'abbreviation' => 'MJK',
									'license_plate' => 'S',
	        					],
								[
		        					'name' => 'Kabupaten Jombang',
									'code' => '35.17',
		        					'abbreviation' => 'JBG',
									'license_plate' => 'S',
	        					],
								[
		        					'name' => 'Kabupaten Nganjuk',
									'code' => '35.18',
		        					'abbreviation' => 'NJK',
									'license_plate' => 'AG',
	        					],
								[
		        					'name' => 'Kabupaten Madiun',
									'code' => '35.19',
		        					'abbreviation' => 'MJY',
									'license_plate' => 'AE',
	        					],
								[
		        					'name' => 'Kabupaten Magetan',
									'code' => '35.20',
		        					'abbreviation' => 'MGT',
									'license_plate' => 'AE',
	        					],
								[
		        					'name' => 'Kabupaten Ngawi',
									'code' => '35.21',
		        					'abbreviation' => 'NGW',
									'license_plate' => 'AE',
	        					],
								[
		        					'name' => 'Kabupaten Bojonegoro',
									'code' => '35.22',
		        					'abbreviation' => 'BJN',
									'license_plate' => 'S',
	        					],
								[
		        					'name' => 'Kabupaten Tuban',
									'code' => '35.23',
		        					'abbreviation' => 'TBN',
									'license_plate' => 'S',
	        					],
								[
		        					'name' => 'Kabupaten Lamongan',
									'code' => '35.24',
		        					'abbreviation' => 'LMG',
									'license_plate' => 'S',
	        					],
								[
		        					'name' => 'Kabupaten Gresik',
									'code' => '35.25',
		        					'abbreviation' => 'GSK',
									'license_plate' => 'W',
	        					],
								[
		        					'name' => 'Kabupaten Bangkalan',
									'code' => '35.26',
		        					'abbreviation' => 'BKL',
									'license_plate' => 'M',
	        					],
								[
		        					'name' => 'Kabupaten Sampang',
									'code' => '35.27',
		        					'abbreviation' => 'SPG',
									'license_plate' => 'M',
	        					],
								[
		        					'name' => 'Kabupaten Pamekasan',
									'code' => '35.28',
		        					'abbreviation' => 'PMK',
									'license_plate' => 'M',
	        					],
								[
		        					'name' => 'Kabupaten Sumenep',
									'code' => '35.29',
		        					'abbreviation' => 'SMP',
									'license_plate' => 'M',
	        					],
								[
		        					'name' => 'Kota Kediri',
									'code' => '35.71',
		        					'abbreviation' => 'KDR',
									'license_plate' => 'AG',
	        					],
								[
		        					'name' => 'Kota Blitar',
									'code' => '35.72',
		        					'abbreviation' => 'BLT',
									'license_plate' => 'AG',
	        					],
								[
		        					'name' => 'Kota Malang',
									'code' => '35.73',
		        					'abbreviation' => 'MLG',
									'license_plate' => 'N',
	        					],
								[
		        					'name' => 'Kota Probolinggo',
									'code' => '35.74',
		        					'abbreviation' => 'PBL',
									'license_plate' => 'N',
	        					],
								[
		        					'name' => 'Kota Pasuruan',
									'code' => '35.75',
		        					'abbreviation' => 'PSN',
									'license_plate' => 'N',
	        					],
								[
		        					'name' => 'Kota Mojokerto',
									'code' => '35.76',
		        					'abbreviation' => 'MJK',
									'license_plate' => 'S',
	        					],
								[
		        					'name' => 'Kota Madiun',
									'code' => '35.77',
		        					'abbreviation' => 'MAD',
									'license_plate' => 'AE',
	        					],
								[
		        					'name' => 'Kota Surabaya',
									'code' => '35.78',
		        					'abbreviation' => 'SBY',
									'license_plate' => 'L',
	        					],
								[
		        					'name' => 'Kota Batu',
									'code' => '35.79',
		        					'abbreviation' => 'BTU',
									'license_plate' => 'N',
	        					],
	        				],
	        			],
	        			[
	        				'name' => 'DI Yogyakarta',
							'code' => '34',
	        				'abbreviation' => 'DIY',
	        				'regencies' => [
	        					[
									'name' => 'Kabupaten Kulon Progo',
									'code' => '34.01',
		        					'abbreviation' => 'WAT',
									'license_plate' => 'AB',
	        					],
								[
		        					'name' => 'Kabupaten Bantul',
									'code' => '34.02',
		        					'abbreviation' => 'BTL',
									'license_plate' => 'AB',
	        					],
								[
		        					'name' => 'Kabupaten Gunung Kidul',
									'code' => '34.03',
		        					'abbreviation' => 'WNO',
									'license_plate' => 'AB',
	        					],
								[
		        					'name' => 'Kabupaten Sleman',
									'code' => '34.04',
		        					'abbreviation' => 'SMN',
									'license_plate' => 'AB',
	        					],
								[
		        					'name' => 'Kota Yogyakarta',
									'code' => '34.71',
		        					'abbreviation' => 'YYK',
									'license_plate' => 'AB',
	        					],
	        				],
	        			],
	        		]
        		],
			],
        	[
        		'island' => [
					'name' => 'Kalimantan',
					'code' => '60',
	        		'provinces' => [
	        			[
							'name' => 'Kalimantan Barat',
							'code' => '61',
	        				'abbreviation' => 'Kalbar',
	        				'regencies' => [
	        					[
									'name' => 'Kabupaten Sambas',
									'code' => '61.01',
		        					'abbreviation' => 'SBS',
									'license_plate' => 'KB',
	        					],
								[
		        					'name' => 'Kabupaten Bengkayang',
									'code' => '61.07',
		        					'abbreviation' => 'BEK',
									'license_plate' => 'KB',
	        					],
								[
		        					'name' => 'Kabupaten Landak',
									'code' => '61.08',
		        					'abbreviation' => 'NBA',
									'license_plate' => 'KB',
	        					],
								[
		        					'name' => 'Kabupaten Mempawah',
									'code' => '61.02',
		        					'abbreviation' => 'MPW',
									'license_plate' => 'KB',
	        					],
								[
		        					'name' => 'Kabupaten Sanggau',
									'code' => '61.03',
		        					'abbreviation' => 'SAG',
									'license_plate' => 'KB',
	        					],
								[
		        					'name' => 'Kabupaten Ketapang',
									'code' => '61.04',
		        					'abbreviation' => 'KTP',
									'license_plate' => 'KB',
	        					],
								[
		        					'name' => 'Kabupaten Sintang',
									'code' => '61.05',
		        					'abbreviation' => 'STG',
									'license_plate' => 'KB',
	        					],
								[
		        					'name' => 'Kabupaten Kapuas Hulu',
									'code' => '61.06',
		        					'abbreviation' => 'PTS',
									'license_plate' => 'KB',
	        					],
								[
		        					'name' => 'Kabupaten Sekadau',
									'code' => '61.09',
		        					'abbreviation' => 'SED',
									'license_plate' => 'KB',
	        					],
								[
		        					'name' => 'Kabupaten Melawi',
									'code' => '61.10',
		        					'abbreviation' => 'NGP',
									'license_plate' => 'KB',
	        					],
								[
		        					'name' => 'Kabupaten Kayong Utara',
									'code' => '61.11',
		        					'abbreviation' => 'SKD',
									'license_plate' => 'KB',
	        					],
								[
		        					'name' => 'Kabupaten Kubu Raya',
									'code' => '61.12',
		        					'abbreviation' => 'SRY',
									'license_plate' => 'KB',
	        					],
								[
		        					'name' => 'Kota Pontianak',
									'code' => '61.71',
		        					'abbreviation' => 'PTK',
									'license_plate' => 'KB',
	        					],
								[
		        					'name' => 'Kota Singkawang',
									'code' => '61.72',
		        					'abbreviation' => 'SKW',
									'license_plate' => 'KB',
	        					],
	        				],
	        			],
	        			[
							'name' => 'Kalimantan Selatan',
							'code' => '63',
	        				'abbreviation' => 'Kalsel',
	        				'regencies' => [
	        					[
									'name' => 'Kabupaten Tanah Laut',
									'code' => '63.01',
		        					'abbreviation' => 'PLI',
									'license_plate' => 'DA',
	        					],
								[
		        					'name' => 'Kabupaten Kota Baru',
									'code' => '63.02',
		        					'abbreviation' => 'KBR',
									'license_plate' => 'DA',
	        					],
								[
		        					'name' => 'Kabupaten Banjar',
									'code' => '63.03',
		        					'abbreviation' => 'MTP',
									'license_plate' => 'DA',
	        					],
								[
		        					'name' => 'Kabupaten Barito Kuala',
									'code' => '63.04',
		        					'abbreviation' => 'MRH',
									'license_plate' => 'DA',
	        					],
								[
		        					'name' => 'Kabupaten Tapin',
									'code' => '63.05',
		        					'abbreviation' => 'RTA',
									'license_plate' => 'DA',
	        					],
								[
		        					'name' => 'Kabupaten Hulu Sungai Selatan',
									'code' => '63.06',
		        					'abbreviation' => 'KGN',
									'license_plate' => 'DA',
	        					],
								[
		        					'name' => 'Kabupaten Hulu Sungai Tengah',
									'code' => '63.07',
		        					'abbreviation' => 'BRB',
									'license_plate' => 'DA',
	        					],
								[
		        					'name' => 'Kabupaten Hulu Sungai Utara',
									'code' => '63.08',
		        					'abbreviation' => 'AMT',
									'license_plate' => 'DA',
	        					],
								[
		        					'name' => 'Kabupaten Tabalong',
									'code' => '63.09',
		        					'abbreviation' => 'TJG',
									'license_plate' => 'DA',
	        					],
								[
		        					'name' => 'Kabupaten Tanah Bumbu',
									'code' => '63.10',
		        					'abbreviation' => 'BLN',
									'license_plate' => 'DA',
	        					],
								[
		        					'name' => 'Kabupaten Balangan',
									'code' => '63.11',
		        					'abbreviation' => 'PRN',
									'license_plate' => 'DA',
	        					],
								[
		        					'name' => 'Kota Banjarmasin',
									'code' => '63.71',
		        					'abbreviation' => 'BJM',
									'license_plate' => 'DA',
	        					],
								[
		        					'name' => 'Kota Banjar Baru',
									'code' => '63.72',
		        					'abbreviation' => 'BJB',
									'license_plate' => 'DA',
	        					],
	        				],
	        			],
	        			[
							'name' => 'Kalimantan Tengah',
							'code' => '62',
	        				'abbreviation' => 'Kalteng',
	        				'regencies' => [
	        					[
									'name' => 'Kabupaten Kotawaringin Barat',
									'code' => '62.01',
		        					'abbreviation' => 'PBU',
									'license_plate' => 'KH',
	        					],
								[
		        					'name' => 'Kabupaten Kotawaringin Timur',
									'code' => '62.02',
		        					'abbreviation' => 'SPT',
									'license_plate' => 'KH',
	        					],
								[
		        					'name' => 'Kabupaten Kapuas',
									'code' => '62.03',
		        					'abbreviation' => 'KLK',
									'license_plate' => 'KH',
	        					],
								[
		        					'name' => 'Kabupaten Barito Selatan',
									'code' => '62.04',
		        					'abbreviation' => 'BNT',
									'license_plate' => 'KH',
	        					],
								[
		        					'name' => 'Kabupaten Barito Utara',
									'code' => '62.05',
		        					'abbreviation' => 'MTW',
									'license_plate' => 'KH',
	        					],
								[
		        					'name' => 'Kabupaten Sukamara',
									'code' => '62.08',
		        					'abbreviation' => 'SKR',
									'license_plate' => 'KH',
	        					],
								[
		        					'name' => 'Kabupaten Lamandau',
									'code' => '62.09',
		        					'abbreviation' => 'NGB',
									'license_plate' => 'KH',
	        					],
								[
		        					'name' => 'Kabupaten Seruyan',
									'code' => '62.07',
		        					'abbreviation' => 'KLP',
									'license_plate' => 'KH',
	        					],
								[
		        					'name' => 'Kabupaten Katingan',
									'code' => '62.06',
		        					'abbreviation' => 'KSN',
									'license_plate' => 'KH',
	        					],
								[
		        					'name' => 'Kabupaten Pulang Pisau',
									'code' => '62.11',
		        					'abbreviation' => 'PPS',
									'license_plate' => 'KH',
	        					],
								[
		        					'name' => 'Kabupaten Gunung Mas',
									'code' => '62.10',
		        					'abbreviation' => 'KKN',
									'license_plate' => 'KH',
	        					],
								[
		        					'name' => 'Kabupaten Barito Timur',
									'code' => '62.13',
		        					'abbreviation' => 'TML',
									'license_plate' => 'KH',
	        					],
								[
		        					'name' => 'Kabupaten Murung Raya',
									'code' => '62.12',
		        					'abbreviation' => 'PRC',
									'license_plate' => 'KH',
	        					],
								[
		        					'name' => 'Kota Palangka Raya',
									'code' => '62.71',
		        					'abbreviation' => 'PLK',
									'license_plate' => 'KH',
	        					],
	        				],
	        			],
	        			[
							'name' => 'Kalimantan Timur',
							'code' => '64',
	        				'abbreviation' => 'Kaltim',
	        				'regencies' => [
	        					[
		        					'name' => 'Kabupaten Paser',
									'code' => '64.01',
		        					'abbreviation' => 'TGT',
									'license_plate' => 'KT',
	        					],
								[
		        					'name' => 'Kabupaten Kutai Barat',
									'code' => '64.07',
		        					'abbreviation' => 'SDW',
									'license_plate' => 'KT',
	        					],
								[
		        					'name' => 'Kabupaten Kutai Kartanegara',
									'code' => '64.02',
		        					'abbreviation' => 'TRG',
									'license_plate' => 'KT',
	        					],
								[
		        					'name' => 'Kabupaten Kutai Timur',
									'code' => '64.08',
		        					'abbreviation' => 'SGT',
									'license_plate' => 'KT',
	        					],
								[
		        					'name' => 'Kabupaten Berau',
									'code' => '64.03',
		        					'abbreviation' => 'TNR',
									'license_plate' => 'KT',
	        					],
								[
		        					'name' => 'Kabupaten Penajam Paser Utara',
									'code' => '64.09',
		        					'abbreviation' => 'PNJ',
									'license_plate' => 'KT',
	        					],
								[
		        					'name' => 'Kabupaten Mahakam Hulu',
									'code' => '64.11',
		        					'abbreviation' => 'UBL',
									'license_plate' => 'KT',
	        					],
								[
		        					'name' => 'Kota Balikpapan',
									'code' => '64.71',
		        					'abbreviation' => 'BPP',
									'license_plate' => 'KT',
	        					],
								[
		        					'name' => 'Kota Samarinda',
									'code' => '64.72',
		        					'abbreviation' => 'SMR',
									'license_plate' => 'KT',
	        					],
								[
		        					'name' => 'Kota Bontang',
									'code' => '64.74',
		        					'abbreviation' => 'BON',
									'license_plate' => 'KT',
	        					],
	        				],
	        			],
	        			[
							'name' => 'Kalimantan Utara',
							'code' => '65',
	        				'abbreviation' => 'Kalut',
	        				'regencies' => [
	        					[
									'name' => 'Kabupaten Malinau',
									'code' => '65.02',
		        					'abbreviation' => 'MLN',
									'license_plate' => 'KU',
	        					],
								[
		        					'name' => 'Kabupaten Bulungan',
									'code' => '65.01',
		        					'abbreviation' => 'TJS',
									'license_plate' => 'KU',
	        					],
								[
		        					'name' => 'Kabupaten Tana Tidung',
									'code' => '65.04',
		        					'abbreviation' => 'TDP',
									'license_plate' => 'KU',
	        					],
								[
		        					'name' => 'Kabupaten Nunukan',
									'code' => '65.03',
		        					'abbreviation' => 'NNK',
									'license_plate' => 'KU',
	        					],
								[
		        					'name' => 'Kota Tarakan',
									'code' => '65.71',
		        					'abbreviation' => 'TAR',
									'license_plate' => 'KU',
	        					],
	        				],
	        			],
	        		]
        		],
        	],
        	[
        		'island' => [
					'name' => 'Kepulauan Maluku',
					'code' => '80',
	        		'provinces' => [
	        			[
							'name' => 'Maluku',
							'code' => '81',
	        				'abbreviation' => 'Maluku',
	        				'regencies' => [
	        					[
		        					'name' => 'Kabupaten Maluku Tenggara Barat',
									'code' => '81.03',
		        					'abbreviation' => 'SML',
									'license_plate' => 'DE',
	        					],
								[
		        					'name' => 'Kabupaten Maluku Tenggara',
									'code' => '81.02',
		        					'abbreviation' => 'TUL',
									'license_plate' => 'DE',
	        					],
								[
		        					'name' => 'Kabupaten Maluku Tengah',
									'code' => '81.01',
		        					'abbreviation' => 'MSH',
									'license_plate' => 'DE',
	        					],
								[
		        					'name' => 'Kabupaten Buru',
									'code' => '81.04',
		        					'abbreviation' => 'NLA',
									'license_plate' => 'DE',
	        					],
								[
		        					'name' => 'Kabupaten Kepulauan Aru',
									'code' => '81.07',
		        					'abbreviation' => 'DOB',
									'license_plate' => 'DE',
	        					],
								[
		        					'name' => 'Kabupaten Seram Bagian Barat',
									'code' => '81.06',
		        					'abbreviation' => 'DRH',
									'license_plate' => 'DE',
	        					],
								[
		        					'name' => 'Kabupaten Seram Bagian Timur',
									'code' => '81.05',
		        					'abbreviation' => 'DTH',
									'license_plate' => 'DE',
	        					],
								[
		        					'name' => 'Kabupaten Maluku Barat Daya',
									'code' => '81.08',
		        					'abbreviation' => 'TKR',
									'license_plate' => 'DE',
	        					],
								[
		        					'name' => 'Kabupaten Buru Selatan',
									'code' => '81.09',
		        					'abbreviation' => 'NMR',
									'license_plate' => 'DE',
	        					],
								[
		        					'name' => 'Kota Ambon',
									'code' => '81.71',
		        					'abbreviation' => 'AMB',
									'license_plate' => 'DE',
	        					],
								[
		        					'name' => 'Kota Tual',
									'code' => '81.72',
		        					'abbreviation' => 'TUL',
									'license_plate' => 'DE',
	        					],
	        				],
	        			],
	        			[
							'name' => 'Maluku Utara',
							'code' => '82',
	        				'abbreviation' => 'Malut',
	        				'regencies' => [
	        					[
		        					'name' => 'Kabupaten Halmahera Barat',
									'code' => '82.01',
									'abbreviation' => 'JLL',
									'license_plate' => 'DG',
	        					],
								[
		        					'name' => 'Kabupaten Halmahera Tengah',
									'code' => '82.02',
									'abbreviation' => 'WED',
									'license_plate' => 'DG',
	        					],
								[
		        					'name' => 'Kabupaten Kepulauan Sula',
									'code' => '82.05',
									'abbreviation' => 'SNN',
									'license_plate' => 'DG',
	        					],
								[
		        					'name' => 'Kabupaten Halmahera Selatan',
									'code' => '82.04',
									'abbreviation' => 'LBA',
									'license_plate' => 'DG',
	        					],
								[
		        					'name' => 'Kabupaten Halmahera Utara',
									'code' => '82.03',
									'abbreviation' => 'TOB',
									'license_plate' => 'DG',
	        					],
								[
		        					'name' => 'Kabupaten Halmahera Timur',
									'code' => '82.06',
									'abbreviation' => 'MAB',
									'license_plate' => 'DG',
	        					],
								[
		        					'name' => 'Kabupaten Pulau Morotai',
									'code' => '82.07',
									'abbreviation' => 'MTS',
									'license_plate' => 'DG',
	        					],
								[
		        					'name' => 'Kabupaten Pulau Taliabu',
									'code' => '82.08',
									'abbreviation' => 'BBG',
									'license_plate' => 'DG',
	        					],
								[
		        					'name' => 'Kota Ternate',
									'code' => '82.71',
									'abbreviation' => 'TTE',
									'license_plate' => 'DG',
	        					],
								[
		        					'name' => 'Kota Tidore Kepulauan',
									'code' => '82.72',
									'abbreviation' => 'TDR',
									'license_plate' => 'DG',
	        					],
	        				],
	        			],
	        		]
        		],
        	],
        	[
        		'island' => [
					'name' => 'Kepulauan Nusa Tenggara',
					'code' => '50',
	        		'provinces' => [
	        			[
							'name' => 'Bali',
							'code' => '51',
	        				'abbreviation' => 'Bali',
	        				'regencies' => [
	        					[
		        					'name' => 'Kabupaten Badung',
									'code' => '51.03',
									'abbreviation' => 'MGW',
									'license_plate' => 'DK',
	        					],
								[
		        					'name' => 'Kabupaten Bangli',
									'code' => '51.06',
									'abbreviation' => 'BLI',
									'license_plate' => 'DK',
	        					],
								[
		        					'name' => 'Kabupaten Buleleng',
									'code' => '51.08',
									'abbreviation' => 'SGR',
									'license_plate' => 'DK',
	        					],
								[
		        					'name' => 'Kabupaten Gianyar',
									'code' => '51.04',
									'abbreviation' => 'GIN',
									'license_plate' => 'DK',
	        					],
								[
		        					'name' => 'Kabupaten Jembrana',
									'code' => '51.01',
									'abbreviation' => 'NGA',
									'license_plate' => 'DK',
	        					],
								[
		        					'name' => 'Kabupaten Karang Asem',
									'code' => '51.07',
									'abbreviation' => 'KRA',
									'license_plate' => 'DK',
	        					],
								[
		        					'name' => 'Kabupaten Klungkung',
									'code' => '51.05',
									'abbreviation' => 'SRP',
									'license_plate' => 'DK',
	        					],
								[
		        					'name' => 'Kabupaten Tabanan',
									'code' => '51.02',
									'abbreviation' => 'TAB',
									'license_plate' => 'DK',
	        					],
								[
		        					'name' => 'Kota Denpasar',
									'code' => '51.71',
									'abbreviation' => 'DPR',
									'license_plate' => 'DK',
	        					],
	        				],
	        			],
						[
							'name' => 'Nusa Tenggara Barat',
							'code' => '52',
	        				'abbreviation' => 'NTB',
	        				'regencies' => [
	        					[
		        					'name' => 'Kabupaten Bima',
									'code' => '52.06',
									'abbreviation' => 'WHO',
									'license_plate' => 'EA',
	        					],
								[
		        					'name' => 'Kabupaten Dompu',
									'code' => '52.05',
									'abbreviation' => 'DPU',
									'license_plate' => 'EA',
	        					],
								[
		        					'name' => 'Kabupaten Lombok Barat',
									'code' => '52.01',
									'abbreviation' => 'GRG',
									'license_plate' => 'DR',
	        					],
								[
		        					'name' => 'Kabupaten Lombok Tengah',
									'code' => '52.02',
									'abbreviation' => 'PYA',
									'license_plate' => 'DR',
	        					],
								[
		        					'name' => 'Kabupaten Lombok Timur',
									'code' => '52.03',
									'abbreviation' => 'SEL',
									'license_plate' => 'DR',
	        					],
								[
		        					'name' => 'Kabupaten Lombok Utara',
									'code' => '52.08',
									'abbreviation' => 'TJN',
									'license_plate' => 'DR',
	        					],
								[
		        					'name' => 'Kabupaten Sumbawa',
									'code' => '52.04',
									'abbreviation' => 'SBW',
									'license_plate' => 'EA',
	        					],
								[
		        					'name' => 'Kabupaten Sumbawa Barat',
									'code' => '52.07',
									'abbreviation' => 'TLW',
									'license_plate' => 'EA',
	        					],
								[
		        					'name' => 'Kota Bima',
									'code' => '52.72',
									'abbreviation' => 'BIM',
									'license_plate' => 'EA',
	        					],
								[
		        					'name' => 'Kota Mataram',
									'code' => '52.71',
									'abbreviation' => 'MTR',
									'license_plate' => 'DR',
	        					],
	        				],
	        			],
						[
							'name' => 'Nusa Tenggara Timur',
							'code' => '53',
	        				'abbreviation' => 'NTT',
	        				'regencies' => [
	        					[
		        					'name' => 'Kabupaten Alor',
									'code' => '53.05',
		        					'abbreviation' => 'KLB',
									'license_plate' => 'EB',
	        					],
								[
		        					'name' => 'Kabupaten Belu',
									'code' => '53.04',
		        					'abbreviation' => 'ATB',
									'license_plate' => 'DH',
	        					],
								[
		        					'name' => 'Kabupaten Ende',
									'code' => '53.08',
		        					'abbreviation' => 'END',
									'license_plate' => 'EB',
	        					],
								[
		        					'name' => 'Kabupaten Flores Timur',
									'code' => '53.06',
		        					'abbreviation' => 'LRT',
									'license_plate' => 'EB',
	        					],
								[
		        					'name' => 'Kabupaten Kupang',
									'code' => '53.01',
		        					'abbreviation' => 'KPG',
									'license_plate' => 'DH',
	        					],
								[
		        					'name' => 'Kabupaten Lembata',
									'code' => '53.13',
		        					'abbreviation' => 'LWL',
									'license_plate' => 'EB',
	        					],
								[
		        					'name' => 'Kabupaten Malaka',
									'code' => '53.21',
		        					'abbreviation' => 'BTN',
									'license_plate' => 'DH',
	        					],
								[
		        					'name' => 'Kabupaten Manggarai',
									'code' => '53.10',
		        					'abbreviation' => 'RTG',
									'license_plate' => 'EB',
	        					],
								[
		        					'name' => 'Kabupaten Manggarai Barat',
									'code' => '53.15',
		        					'abbreviation' => 'LBJ',
									'license_plate' => 'EB',
	        					],
								[
		        					'name' => 'Kabupaten Manggarai Timur',
									'code' => '53.19',
		        					'abbreviation' => 'BRG',
									'license_plate' => 'EB',
	        					],
								[
		        					'name' => 'Kabupaten Nagekeo',
									'code' => '53.16',
		        					'abbreviation' => 'MBY',
									'license_plate' => 'EB',
	        					],
								[
		        					'name' => 'Kabupaten Ngada',
									'code' => '53.09',
		        					'abbreviation' => 'BJW',
									'license_plate' => 'EB',
	        					],
								[
		        					'name' => 'Kabupaten Rote Ndao',
									'code' => '53.14',
		        					'abbreviation' => 'BAA',
									'license_plate' => 'DH',
	        					],
								[
		        					'name' => 'Kabupaten Sabu Raijua',
									'code' => '53.20',
		        					'abbreviation' => 'SBB',
									'license_plate' => 'DH',
	        					],
								[
		        					'name' => 'Kabupaten Sikka',
									'code' => '53.07',
		        					'abbreviation' => 'MME',
									'license_plate' => 'EB',
	        					],
								[
		        					'name' => 'Kabupaten Sumba Barat',
									'code' => '53.12',
		        					'abbreviation' => 'WKB',
									'license_plate' => 'ED',
	        					],
								[
		        					'name' => 'Kabupaten Sumba Barat Daya',
									'code' => '53.18',
		        					'abbreviation' => 'TAM',
									'license_plate' => 'ED',
	        					],
								[
		        					'name' => 'Kabupaten Sumba Tengah',
									'code' => '53.17',
		        					'abbreviation' => 'WBL',
									'license_plate' => 'ED',
	        					],
								[
		        					'name' => 'Kabupaten Sumba Timur',
									'code' => '53.11',
		        					'abbreviation' => 'WGP',
									'license_plate' => 'ED',
	        					],
								[
		        					'name' => 'Kabupaten Timor Tengah Selatan',
									'code' => '53.02',
		        					'abbreviation' => 'SOE',
									'license_plate' => 'DH',
	        					],
								[
		        					'name' => 'Kabupaten Timor Tengah Utara',
									'code' => '53.03',
		        					'abbreviation' => 'KFM',
									'license_plate' => 'DH',
	        					],
								[
		        					'name' => 'Kota Kupang',
									'code' => '53.71',
		        					'abbreviation' => 'KPG',
									'license_plate' => 'DH',
	        					],
	        				],
	        			],
	        		]
        		],
        	],
        	[
        		'island' => [
					'name' => 'Papua',
					'code' => '90',
	        		'provinces' => [
	        			[
							'name' => 'Papua',
							'code' => '91',
	        				'abbreviation' => 'Papua',
	        				'regencies' => [
	        					[
									'name' => 'Kabupaten Asmat',
									'code' => '91.18',
		        					'abbreviation' => 'AGT',
									'license_plate' => 'PA',
	        					],
								[
		        					'name' => 'Kabupaten Biak Numfor',
									'code' => '91.06',
		        					'abbreviation' => 'BIK',
									'license_plate' => 'PA',
	        					],
								[
		        					'name' => 'Kabupaten Boven Digoel',
									'code' => '91.16',
		        					'abbreviation' => 'TMR',
									'license_plate' => 'PA',
	        					],
								[
		        					'name' => 'Kabupaten Deiyai',
									'code' => '91.28',
		        					'abbreviation' => 'TIG',
									'license_plate' => 'PA',
	        					],
								[
		        					'name' => 'Kabupaten Dogiyai',
									'code' => '91.26',
		        					'abbreviation' => 'KGM',
									'license_plate' => 'PA',
	        					],
								[
		        					'name' => 'Kabupaten Intan Jaya',
									'code' => '91.27',
		        					'abbreviation' => 'SGP',
									'license_plate' => 'PA',
	        					],
								[
		        					'name' => 'Kabupaten Jayapura',
									'code' => '91.03',
		        					'abbreviation' => 'JAP',
									'license_plate' => 'PA',
	        					],
								[
		        					'name' => 'Kabupaten Jayawijaya',
									'code' => '91.02',
		        					'abbreviation' => 'WAM',
									'license_plate' => 'PA',
	        					],
								[
		        					'name' => 'Kabupaten Keerom',
									'code' => '91.11',
		        					'abbreviation' => 'WRS',
									'license_plate' => 'PA',
	        					],
								[
		        					'name' => 'Kabupaten Kepulauan Yapen',
									'code' => '91.05',
		        					'abbreviation' => 'SRU',
									'license_plate' => 'PA',
	        					],
								[
		        					'name' => 'Kabupaten Lanny Jaya',
									'code' => '91.23',
		        					'abbreviation' => 'TOM',
									'license_plate' => 'PA',
	        					],
								[
		        					'name' => 'Kabupaten Mamberamo Raya',
									'code' => '91.20',
		        					'abbreviation' => 'BRM',
									'license_plate' => 'PA',
	        					],
								[
		        					'name' => 'Kabupaten Mamberamo Tengah',
									'code' => '91.21',
		        					'abbreviation' => 'KBK',
									'license_plate' => 'PA',
	        					],
								[
		        					'name' => 'Kabupaten Mappi',
									'code' => '91.17',
		        					'abbreviation' => 'KEP',
									'license_plate' => 'PA',
	        					],
								[
		        					'name' => 'Kabupaten Merauke',
									'code' => '91.01',
		        					'abbreviation' => 'MRK',
									'license_plate' => 'PA',
	        					],
								[
		        					'name' => 'Kabupaten Mimika',
									'code' => '91.09',
		        					'abbreviation' => 'TIM',
									'license_plate' => 'PA',
	        					],
								[
		        					'name' => 'Kabupaten Nabire',
									'code' => '91.04',
		        					'abbreviation' => 'NAB',
									'license_plate' => 'PA',
	        					],
								[
		        					'name' => 'Kabupaten Nduga',
									'code' => '91.24',
		        					'abbreviation' => 'KYM',
									'license_plate' => 'PA',
	        					],
								[
		        					'name' => 'Kabupaten Paniai',
									'code' => '91.08',
		        					'abbreviation' => 'ERT',
									'license_plate' => 'PA',
	        					],
								[
		        					'name' => 'Kabupaten Pegunungan Bintang',
									'code' => '91.12',
		        					'abbreviation' => 'OSB',
									'license_plate' => 'PA',
	        					],
								[
		        					'name' => 'Kabupaten Puncak',
									'code' => '91.25',
		        					'abbreviation' => 'ILG',
									'license_plate' => 'PA',
	        					],
								[
		        					'name' => 'Kabupaten Puncak Jaya',
									'code' => '91.07',
		        					'abbreviation' => 'MUL',
									'license_plate' => 'PA',
	        					],
								[
		        					'name' => 'Kabupaten Sarmi',
									'code' => '91.10',
		        					'abbreviation' => 'SMI',
									'license_plate' => 'PA',
	        					],
								[
		        					'name' => 'Kabupaten Supiori',
									'code' => '91.19',
		        					'abbreviation' => 'SRW',
									'license_plate' => 'PA',
	        					],
								[
		        					'name' => 'Kabupaten Tolikara',
									'code' => '91.14',
		        					'abbreviation' => 'KBG',
									'license_plate' => 'PA',
	        					],
								[
		        					'name' => 'Kabupaten Waropen',
									'code' => '91.15',
		        					'abbreviation' => 'BTW',
									'license_plate' => 'PA',
	        					],
								[
		        					'name' => 'Kabupaten Yahukimo',
									'code' => '91.13',
		        					'abbreviation' => 'SMH',
									'license_plate' => 'PA',
	        					],
								[
		        					'name' => 'Kabupaten Yalimo',
									'code' => '91.22',
		        					'abbreviation' => 'ELL',
									'license_plate' => 'PA',
	        					],
								[
		        					'name' => 'Kota Jayapura',
									'code' => '91.71',
		        					'abbreviation' => 'JAP',
									'license_plate' => 'PA',
	        					],
	        				],
	        			],
						[
	        				'name' => 'Papua Barat',
							'code' => '92',
							'abbreviation' => 'Papua Barat',
	        				'regencies' => [
	        					[
		        					'name' => 'Kabupaten Fakfak',
									'code' => '92.03',
		        					'abbreviation' => 'FFK',
									'license_plate' => 'PB',
	        					],
								[
		        					'name' => 'Kabupaten Kaimana',
									'code' => '92.08',
		        					'abbreviation' => 'KMN',
									'license_plate' => 'PB',
	        					],
								[
		        					'name' => 'Kabupaten Manokwari',
									'code' => '92.02',
		        					'abbreviation' => 'MNK',
									'license_plate' => 'PB',
	        					],
								[
		        					'name' => 'Kabupaten Manokwari Selatan',
									'code' => '92.11',
		        					'abbreviation' => 'RSK',
									'license_plate' => 'PB',
	        					],
								[
		        					'name' => 'Kabupaten Maybrat',
									'code' => '92.10',
		        					'abbreviation' => 'AFT',
									'license_plate' => 'PB',
	        					],
								[
		        					'name' => 'Kabupaten Pegunungan Arfak',
									'code' => '92.12',
		        					'abbreviation' => 'ANG',
									'license_plate' => 'PB',
	        					],
								[
		        					'name' => 'Kabupaten Raja Ampat',
									'code' => '92.05',
		        					'abbreviation' => 'WAS',
									'license_plate' => 'PB',
	        					],
								[
		        					'name' => 'Kabupaten Sorong',
									'code' => '92.01',
		        					'abbreviation' => 'AMS',
									'license_plate' => 'PB',
	        					],
								[
		        					'name' => 'Kabupaten Sorong Selatan',
									'code' => '92.04',
		        					'abbreviation' => 'TMB',
									'license_plate' => 'PB',
	        					],
								[
		        					'name' => 'Kabupaten Tambrauw',
									'code' => '92.09',
		        					'abbreviation' => 'FEF',
									'license_plate' => 'PB',
	        					],
								[
		        					'name' => 'Kabupaten Teluk Bintuni',
									'code' => '92.06',
		        					'abbreviation' => 'BTI',
									'license_plate' => 'PB',
	        					],
								[
		        					'name' => 'Kabupaten Teluk Wondama',
									'code' => '92.07',
		        					'abbreviation' => 'RAS',
									'license_plate' => 'PB',
	        					],
								[
		        					'name' => 'Kota Sorong',
									'code' => '92.71',
		        					'abbreviation' => 'SON',
									'license_plate' => 'PB',
	        					],
	        				],
	        			],
	        		]
        		],
        	],
        	[
        		'island' => [
        			'name' => 'Sulawesi',
					'code' => '70',
	        		'provinces' => [
	        			[
							'name' => 'Gorontalo',
							'code' => '75',
	        				'abbreviation' => 'Gorontalo',
	        				'regencies' => [
	        					[
		        					'name' => 'Kabupaten Boalemo',
									'code' => '75.02',
									'abbreviation' => 'TMT',
									'license_plate' => 'DM',
	        					],
	        					[
		        					'name' => 'Kabupaten Bone Bolango',
									'code' => '75.03',
									'abbreviation' => 'SWW',
									'license_plate' => 'DM',
	        					],
	        					[
		        					'name' => 'Kabupaten Gorontalo',
									'code' => '75.01',
									'abbreviation' => 'GTO',
									'license_plate' => 'DM',
	        					],
	        					[
		        					'name' => 'Kabupaten Gorontalo Utara',
									'code' => '75.05',
									'abbreviation' => 'KWD',
									'license_plate' => 'DM',
	        					],
	        					[
		        					'name' => 'Kabupaten Pohuwato',
									'code' => '75.04',
									'abbreviation' => 'MAR',
									'license_plate' => 'DM',
	        					],
	        					[
		        					'name' => 'Kota Gorontalo',
									'code' => '75.71',
									'abbreviation' => 'GTO',
									'license_plate' => 'DM',
	        					],
	        				],
	        			],
						[
							'name' => 'Sulawesi Barat',
							'code' => '76',
	        				'abbreviation' => 'Sulbar',
	        				'regencies' => [
	        					[
		        					'name' => 'Kabupaten Majene',
									'code' => '76.05',
									'abbreviation' => 'MJN',
									'license_plate' => 'DC',
	        					],
								[
		        					'name' => 'Kabupaten Mamasa',
									'code' => '76.03',
									'abbreviation' => 'MMS',
									'license_plate' => 'DC',
	        					],
								[
		        					'name' => 'Kabupaten Mamuju',
									'code' => '76.02',
									'abbreviation' => 'MAM',
									'license_plate' => 'DC',
	        					],
								[
		        					'name' => 'Kabupaten Mamuju Tengah',
									'code' => '76.06',
									'abbreviation' => 'TBD',
									'license_plate' => 'DC',
	        					],
								[
		        					'name' => 'Kabupaten Mamuju Utara',
									'code' => '76.01',
									'abbreviation' => 'PKY',
									'license_plate' => 'DC',
	        					],
								[
		        					'name' => 'Kabupaten Polewali Mandar',
									'code' => '76.04',
									'abbreviation' => 'PLW',
									'license_plate' => 'DC',
	        					],
	        				],
	        			],
						[
							'name' => 'Sulawesi Selatan',
							'code' => '73',
	        				'abbreviation' => 'Sulsel',
	        				'regencies' => [
	        					[
		        					'name' => 'Kabupaten Bantaeng',
									'code' => '73.03',
									'abbreviation'=> 'BAN',
									'license_plate' => 'DD',
	        					],
								[
		        					'name' => 'Kabupaten Barru',
									'code' => '73.11',
									'abbreviation' => 'BAR',
									'license_plate' => 'DP',
	        					],
								[
		        					'name' => 'Kabupaten Bone',
									'code' => '73.08',
									'abbreviation' => 'WTP',
									'license_plate' => 'DW',
	        					],
								[
		        					'name' => 'Kabupaten Bulukumba',
									'code' => '73.02',
									'abbreviation' => 'BLK',
									'license_plate' => 'DD',
	        					],
								[
		        					'name' => 'Kabupaten Enrekang',
									'code' => '73.16',
									'abbreviation' => 'ENR',
									'license_plate' => 'DP',
	        					],
								[
		        					'name' => 'Kabupaten Gowa',
									'code' => '73.06',
									'abbreviation' => 'SGM',
									'license_plate' => 'DD',
	        					],
								[
		        					'name' => 'Kabupaten Jeneponto',
									'code' => '73.04',
									'abbreviation' => 'JNP',
									'license_plate' => 'DD',
	        					],
								[
		        					'name' => 'Kabupaten Kepulauan Selayar',
									'code' => '73.01',
									'abbreviation' => 'BEN',
									'license_plate' => 'DD',
	        					],
								[
		        					'name' => 'Kabupaten Luwu',
									'code' => '73.17',
									'abbreviation' => 'PLP',
									'license_plate' => 'DP',
	        					],
								[
		        					'name' => 'Kabupaten Luwu Timur',
									'code' => '73.24',
									'abbreviation' => 'MLL',
									'license_plate' => 'DP',
	        					],
								[
		        					'name' => 'Kabupaten Luwu Utara',
									'code' => '73.22',
									'abbreviation' => 'MSB',
									'license_plate' => 'DP',
	        					],
								[
		        					'name' => 'Kabupaten Maros',
									'code' => '73.09',
									'abbreviation' => 'MRS',
									'license_plate' => 'DD',
	        					],
								[
		        					'name' => 'Kabupaten Pangkajene Dan Kepulauan',
									'code' => '73.10',
									'abbreviation' => 'PKJ',
									'license_plate' => 'DD',
	        					],
								[
		        					'name' => 'Kabupaten Pinrang',
									'code' => '73.15',
									'abbreviation' => 'PIN',
									'license_plate' => 'DP',
	        					],
								[
		        					'name' => 'Kabupaten Sidenreng Rappang',
									'code' => '73.14',
									'abbreviation' => 'SDR',
									'license_plate' => 'DP',
	        					],
								[
		        					'name' => 'Kabupaten Sinjai',
									'code' => '73.07',
									'abbreviation' => 'SNJ',
									'license_plate' => 'DW',
	        					],
								[
		        					'name' => 'Kabupaten Soppeng',
									'code' => '73.12',
									'abbreviation' => 'WNS',
									'license_plate' => 'DW',
	        					],
								[
		        					'name' => 'Kabupaten Takalar',
									'code' => '73.05',
									'abbreviation' => 'TKA',
									'license_plate' => 'DD',
	        					],
								[
		        					'name' => 'Kabupaten Tana Toraja',
									'code' => '73.18',
									'abbreviation' => 'MAK',
									'license_plate' => 'DP',
	        					],
								[
		        					'name' => 'Kabupaten Toraja Utara',
									'code' => '73.26',
									'abbreviation' => 'RTP',
									'license_plate' => 'DP',
	        					],
								[
		        					'name' => 'Kabupaten Wajo',
									'code' => '73.13',
									'abbreviation' => 'SKG',
									'license_plate' => 'DW',
	        					],
								[
		        					'name' => 'Kota Makassar',
									'code' => '73.71',
									'abbreviation' => 'MKS',
									'license_plate' => 'DD',
	        					],
								[
		        					'name' => 'Kota Palopo',
									'code' => '73.73',
									'abbreviation' => 'PLP',
									'license_plate' => 'DP',
	        					],
								[
		        					'name' => 'Kota Parepare',
									'code' => '73.72',
									'abbreviation' => 'PRE',
									'license_plate' => 'DP',
	        					],
	        				],
	        			],
						[
							'name' => 'Sulawesi Tengah',
							'code' => '72',
	        				'abbreviation' => 'Sulteng',
	        				'regencies' => [
	        					[
		        					'name' => 'Kabupaten Banggai',
									'code' => '72.01',
									'abbreviation' => 'LWK',
									'license_plate' => 'DN',
	        					],
								[
		        					'name' => 'Kabupaten Banggai Kepulauan',
									'code' => '72.07',
									'abbreviation' => 'SKN',
									'license_plate' => 'DN',
	        					],
								[
		        					'name' => 'Kabupaten Banggai Laut',
									'code' => '72.11',
									'abbreviation' => 'BGI',
									'license_plate' => 'DN',
	        					],
								[
		        					'name' => 'Kabupaten Buol',
									'code' => '72.05',
									'abbreviation' => 'BUL',
									'license_plate' => 'DN',
	        					],
								[
		        					'name' => 'Kabupaten Donggala',
									'code' => '72.03',
									'abbreviation' => 'DGL',
									'license_plate' => 'DN',
	        					],
								[
		        					'name' => 'Kabupaten Morowali',
									'code' => '72.06',
									'abbreviation' => 'BGK',
									'license_plate' => 'DN',
	        					],
								[
		        					'name' => 'Kabupaten Morowali Utara',
									'code' => '72.12',
									'abbreviation' => 'KLD',
									'license_plate' => 'DN',
	        					],
								[
		        					'name' => 'Kabupaten Parigi Moutong',
									'code' => '72.08',
									'abbreviation' => 'PRG',
									'license_plate' => 'DN',
	        					],
								[
		        					'name' => 'Kabupaten Poso',
									'code' => '72.02',
									'abbreviation' => 'PSO',
									'license_plate' => 'DN',
	        					],
								[
		        					'name' => 'Kabupaten Sigi',
									'code' => '72.10',
									'abbreviation' => 'SGB',
									'license_plate' => 'DN',
	        					],
								[
		        					'name' => 'Kabupaten Tojo Una-Una',
									'code' => '72.09',
									'abbreviation' => 'APN',
									'license_plate' => 'DN',
	        					],
								[
		        					'name' => 'Kabupaten Toli-Toli',
									'code' => '72.04',
									'abbreviation' => 'TLI',
									'license_plate' => 'DN',
	        					],
								[
		        					'name' => 'Kota Palu',
									'code' => '72.71',
									'abbreviation' => 'PAL',
									'license_plate' => 'DN',
	        					],
	        				],
	        			],
						[
							'name' => 'Sulawesi Tenggara',
							'code' => '74',
	        				'abbreviation' => 'Sultra',
	        				'regencies' => [
	        					[
		        					'name' => 'Kabupaten Bombana',
									'code' => '74.06',
									'abbreviation' => 'RMB',
									'license_plate' => 'DT',
	        					],
								[
		        					'name' => 'Kabupaten Buton',
									'code' => '74.04',
									'abbreviation' => 'PSW',
									'license_plate' => 'DT',
	        					],
								[
		        					'name' => 'Kabupaten Buton Selatan',
									'code' => '74.15',
									'abbreviation' => 'BGA',
									'license_plate' => 'DT',
	        					],
								[
		        					'name' => 'Kabupaten Buton Tengah',
									'code' => '74.14',
									'abbreviation' => 'LBK',
									'license_plate' => 'DT',
	        					],
								[
		        					'name' => 'Kabupaten Buton Utara',
									'code' => '74.10',
									'abbreviation' => 'BNG',
									'license_plate' => 'DT',
	        					],
								[
		        					'name' => 'Kabupaten Kolaka',
									'code' => '74.01',
									'abbreviation' => 'KKA',
									'license_plate' => 'DT',
	        					],
								[
		        					'name' => 'Kabupaten Kolaka Timur',
									'code' => '74.11',
									'abbreviation' => 'TWT',
									'license_plate' => 'DT',
	        					],
								[
		        					'name' => 'Kabupaten Kolaka Utara',
									'code' => '74.08',
									'abbreviation' => 'LSS',
									'license_plate' => 'DT',
	        					],
								[
		        					'name' => 'Kabupaten Konawe',
									'code' => '74.02',
									'abbreviation' => 'UNH',
									'license_plate' => 'DT',
	        					],
								[
		        					'name' => 'Kabupaten Konawe Kepulauan',
									'code' => '74.12',
									'abbreviation' => 'LGR',
									'license_plate' => 'DT',
	        					],
								[
		        					'name' => 'Kabupaten Konawe Selatan',
									'code' => '74.05',
									'abbreviation' => 'ADL',
									'license_plate' => 'DT',
	        					],
								[
		        					'name' => 'Kabupaten Konawe Utara',
									'code' => '74.09',
									'abbreviation' => 'WGD',
									'license_plate' => 'DT',
	        					],
								[
		        					'name' => 'Kabupaten Muna',
									'code' => '74.03',
									'abbreviation' => 'RAH',
									'license_plate' => 'DT',
	        					],
								[
		        					'name' => 'Kabupaten Muna Barat',
									'code' => '74.13',
									'abbreviation' => 'LWR',
									'license_plate' => 'DT',
	        					],
								[
		        					'name' => 'Kabupaten Wakatobi',
									'code' => '74.07',
									'abbreviation' => 'WGW',
									'license_plate' => 'DT',
	        					],
								[
		        					'name' => 'Kota Baubau',
									'code' => '74.72',
									'abbreviation' => 'BAU',
									'license_plate' => 'DT',
	        					],
								[
		        					'name' => 'Kota Kendari',
									'code' => '74.71',
									'abbreviation' => 'KDI',
									'license_plate' => 'DT',
	        					],
	        				],
	        			],
						[
							'name' => 'Sulawesi Utara',
							'code' => '71',
	        				'abbreviation' => 'Sulut',
	        				'regencies' => [
	        					[
		        					'name' => 'Kabupaten Bolaang Mongondow',
									'code' => '71.01',
									'abbreviation' => 'LLK',
									'license_plate' => 'DB',
	        					],
								[
		        					'name' => 'Kabupaten Bolaang Mongondow Selatan',
									'code' => '71.11',
									'abbreviation' => 'BLU',
									'license_plate' => 'DB',
	        					],
								[
		        					'name' => 'Kabupaten Bolaang Mongondow Timur',
									'code' => '71.10',
									'abbreviation' => 'TTY',
									'license_plate' => 'DB',
	        					],
								[
		        					'name' => 'Kabupaten Bolaang Mongondow Utara',
									'code' => '71.08',
									'abbreviation' => 'BRK',
									'license_plate' => 'DB',
	        					],
								[
		        					'name' => 'Kabupaten Kepulauan Sangihe',
									'code' => '71.03',
									'abbreviation' => 'THN',
									'license_plate' => 'DL',
	        					],
								[
		        					'name' => 'Kabupaten Kepulauan Talaud',
									'code' => '71.04',
									'abbreviation' => 'MGN',
									'license_plate' => 'DL',
	        					],
								[
		        					'name' => 'Kabupaten Minahasa',
									'code' => '71.02',
									'abbreviation' => 'TNN',
									'license_plate' => 'DB',
	        					],
								[
		        					'name' => 'Kabupaten Minahasa Selatan',
									'code' => '71.05',
									'abbreviation' => 'AMR',
									'license_plate' => 'DB',
	        					],
								[
		        					'name' => 'Kabupaten Minahasa Tenggara',
									'code' => '71.07',
									'abbreviation' => 'RTN',
									'license_plate' => 'DB',
	        					],
								[
		        					'name' => 'Kabupaten Minahasa Utara',
									'code' => '71.06',
									'abbreviation' => 'ARM',
									'license_plate' => 'DB',
	        					],
								[
		        					'name' => 'Kabupaten Siau Tagulandang Biaro',
									'code' => '71.09',
									'abbreviation' => 'ODS',
									'license_plate' => 'DL',
	        					],
								[
		        					'name' => 'Kota Bitung',
									'code' => '71.72',
									'abbreviation' => 'BIT',
									'license_plate' => 'DB',
	        					],
								[
		        					'name' => 'Kota Kotamobagu',
									'code' => '71.74',
									'abbreviation' => 'KTG',
									'license_plate' => 'DB',
	        					],
								[
		        					'name' => 'Kota Manado',
									'code' => '71.71',
									'abbreviation' => 'MND',
									'license_plate' => 'DB',
	        					],
								[
		        					'name' => 'Kota Tomohon',
									'code' => '71.73',
									'abbreviation' => 'TMH',
									'license_plate' => 'DB',
	        					],
	        				],
	        			],
	        		]
        		],
        	],
        	[
        		'island' => [
        			'name' => 'Sumatera',
					'code' => '10',
	        		'provinces' => [
	        			[
							'name' => 'Aceh',
							'code' => '11',
	        				'abbreviation' => 'Aceh',
	        				'regencies' => [
	        					[
		        					'name' => 'Kabupaten Aceh Barat',
									'code' => '11.05',
									'abbreviation' => 'MBO',
									'license_plate' => 'BL',
	        					],
								[
		        					'name' => 'Kabupaten Aceh Barat Daya',
									'code' => '11.12',
									'abbreviation' => 'BPD',
									'license_plate' => 'BL',
	        					],
								[
		        					'name' => 'Kabupaten Aceh Besar',
									'code' => '11.06',
									'abbreviation' => 'JTH',
									'license_plate' => 'BL',
	        					],
								[
		        					'name' => 'Kabupaten Aceh Jaya',
									'code' => '11.14',
									'abbreviation' => 'CAG',
									'license_plate' => 'BL',
	        					],
								[
		        					'name' => 'Kabupaten Aceh Selatan',
									'code' => '11.01',
									'abbreviation' => 'TTN',
									'license_plate' => 'BL',
	        					],
								[
		        					'name' => 'Kabupaten Aceh Singkil',
									'code' => '11.10',
									'abbreviation' => 'SKL',
									'license_plate' => 'BL',
	        					],
								[
		        					'name' => 'Kabupaten Aceh Tamiang',
									'code' => '11.16',
									'abbreviation' => 'KRB',
									'license_plate' => 'BL',
	        					],
								[
		        					'name' => 'Kabupaten Aceh Tengah',
									'code' => '11.04',
									'abbreviation' => 'TKN',
									'license_plate' => 'BL',
	        					],
								[
		        					'name' => 'Kabupaten Aceh Tenggara',
									'code' => '11.02',
									'abbreviation' => 'KTN',
									'license_plate' => 'BL',
	        					],
								[
		        					'name' => 'Kabupaten Aceh Timur',
									'code' => '11.03',
									'abbreviation' => 'LGS',
									'license_plate' => 'BL',
	        					],
								[
		        					'name' => 'Kabupaten Aceh Utara',
									'code' => '11.08',
									'abbreviation' => 'LSK',
									'license_plate' => 'BL',
	        					],
								[
		        					'name' => 'Kabupaten Bener Meriah',
									'code' => '11.17',
									'abbreviation'=> 'STR',
									'license_plate' => 'BL',
	        					],
								[
		        					'name' => 'Kabupaten Bireuen',
									'code' => '11.11',
									'abbreviation' => 'BIR',
									'license_plate' => 'BL',
	        					],
								[
		        					'name' => 'Kabupaten Gayo Lues',
									'code' => '11.13',
									'abbreviation' => 'BKJ',
									'license_plate' => 'BL',
	        					],
								[
		        					'name' => 'Kabupaten Nagan Raya',
									'code' => '11.15',
									'abbreviation' => 'SKM',
									'license_plate' => 'BL',
	        					],
								[
		        					'name' => 'Kabupaten Pidie',
									'code' => '11.07',
									'abbreviation' => 'SGI',
									'license_plate' => 'BL',
	        					],
								[
		        					'name' => 'Kabupaten Pidie Jaya',
									'code' => '11.18',
									'abbreviation' => 'MRN',
									'license_plate' => 'BL',
	        					],
								[
		        					'name' => 'Kabupaten Simeulue',
									'code' => '11.09',
									'abbreviation' => 'SNB',
									'license_plate' => 'BL',
	        					],
								[
		        					'name' => 'Kota Banda Aceh',
									'code' => '11.71',
									'abbreviation' => 'BNA',
									'license_plate' => 'BL',
	        					],
								[
		        					'name' => 'Kota Langsa',
									'code' => '11.74',
									'abbreviation' => 'LGS',
									'license_plate' => 'BL',
	        					],
								[
		        					'name' => 'Kota Lhokseumawe',
									'code' => '11.73',
									'abbreviation' => 'LSM',
									'license_plate' => 'BL',
	        					],
								[
		        					'name' => 'Kota Sabang',
									'code' => '11.72',
									'abbreviation' => 'SAB',
									'license_plate' => 'BL',
	        					],
								[
		        					'name' => 'Kota Subulussalam',
									'code' => '11.75',
									'abbreviation' => 'SUS',
									'license_plate' => 'BL',
	        					],
	        				],
	        			],
						[
							'name' => 'Bengkulu',
							'code' => '17',
	        				'abbreviation' => 'Bengkulu',
	        				'regencies' => [
	        					[
		        					'name' => 'Kabupaten Bengkulu Selatan',
									'code' => '17.01',
									'abbreviation' => 'MNA',
									'license_plate' => 'BD',
	        					],
								[
		        					'name' => 'Kabupaten Bengkulu Tengah',
									'code' => '17.09',
									'abbreviation' => 'KRT',
									'license_plate' => 'BD',
	        					],
								[
		        					'name' => 'Kabupaten Bengkulu Utara',
									'code' => '17.03',
									'abbreviation' => 'AGM',
									'license_plate' => 'BD',
	        					],
								[
		        					'name' => 'Kabupaten Kaur',
									'code' => '17.04',
									'abbreviation' => 'BHN',
									'license_plate' => 'BD',
	        					],
								[
		        					'name' => 'Kabupaten Kepahiang',
									'code' => '17.08',
									'abbreviation' => 'KPH',
									'license_plate' => 'BD',
	        					],
								[
		        					'name' => 'Kabupaten Lebong',
									'code' => '17.07',
									'abbreviation' => 'TUB',
									'license_plate' => 'BD',
	        					],
								[
		        					'name' => 'Kabupaten Mukomuko',
									'code' => '17.06',
									'abbreviation' => 'MKM',
									'license_plate' => 'BD',
	        					],
								[
		        					'name' => 'Kabupaten Rejang Lebong',
									'code' => '17.02',
									'abbreviation' => 'CRP',
									'license_plate' => 'BD',
	        					],
								[
		        					'name' => 'Kabupaten Seluma',
									'code' => '17.05',
									'abbreviation' => 'TAS',
									'license_plate' => 'BD',
	        					],
								[
		        					'name' => 'Kota Bengkulu',
									'code' => '17.71',
									'abbreviation' => 'BGL',
									'license_plate' => 'BD',
	        					],
	        				],
	        			],
						[
							'name' => 'Jambi',
							'code' => '15',
	        				'abbreviation' => 'Jambi',
	        				'regencies' => [
	        					[
		        					'name' => 'Kabupaten Batang Hari',
									'code' => '15.04',
									'abbreviation' => 'MBN',
									'license_plate' => 'BH',
	        					],
								[
		        					'name' => 'Kabupaten Bungo',
									'code' => '15.08',
									'abbreviation' => 'MRB',
									'license_plate' => 'BH',
	        					],
								[
		        					'name' => 'Kabupaten Kerinci',
									'code' => '15.01',
									'abbreviation' => 'SPN',
									'license_plate' => 'BH',
	        					],
								[
		        					'name' => 'Kabupaten Merangin',
									'code' => '15.02',
									'abbreviation' => 'BKO',
									'license_plate' => 'BH',
	        					],
								[
		        					'name' => 'Kabupaten Muaro Jambi',
									'code' => '15.05',
									'abbreviation'=> 'SNT',
									'license_plate' => 'BH',
	        					],
								[
		        					'name' => 'Kabupaten Sarolangun',
									'code' => '15.03',
									'abbreviation' => 'SRL',
									'license_plate' => 'BH',
	        					],
								[
		        					'name' => 'Kabupaten Tanjung Jabung Barat',
									'code' => '15.06',
									'abbreviation' => 'KLT',
									'license_plate' => 'BH',
	        					],
								[
		        					'name' => 'Kabupaten Tanjung Jabung Timur',
									'code' => '15.07',
									'abbreviation' => 'MSK',
									'license_plate' => 'BH',
	        					],
								[
		        					'name' => 'Kabupaten Tebo',
									'code' => '15.09',
									'abbreviation' => 'MRT',
									'license_plate' => 'BH',
	        					],
								[
		        					'name' => 'Kota Jambi',
									'code' => '15.71',
									'abbreviation' => 'JMB',
									'license_plate' => 'BH',
	        					],
								[
		        					'name' => 'Kota Sungai Penuh',
									'code' => '15.72',
									'abbreviation' => 'SPN',
									'license_plate' => 'BH',
	        					],
	        				],
	        			],
						[
							'name' => 'Kepulauan Bangka Belitung',
							'code' => '19',
	        				'abbreviation' => 'B. Belitung',
	        				'regencies' => [
	        					[
		        					'name' => 'Kabupaten Bangka',
									'code' => '19.01',
									'abbreviation' => 'SGL',
									'license_plate' => 'BN',
	        					],
								[
		        					'name' => 'Kabupaten Bangka Barat',
									'code' => '19.05',
									'abbreviation' => 'MTK',
									'license_plate' => 'BN',
	        					],
								[
		        					'name' => 'Kabupaten Bangka Selatan',
									'code' => '19.03',
									'abbreviation' => 'TBL',
									'license_plate' => 'BN',
	        					],
								[
		        					'name' => 'Kabupaten Bangka Tengah',
									'code' => '19.04',
									'abbreviation' => 'KBA',
									'license_plate' => 'BN',
	        					],
								[
		        					'name' => 'Kabupaten Belitung',
									'code' => '19.02',
									'abbreviation' => 'TDN',
									'license_plate' => 'BN',
	        					],
								[
		        					'name' => 'Kabupaten Belitung Timur',
									'code' => '19.06',
									'abbreviation' => 'MGR',
									'license_plate' => 'BN',
	        					],
								[
		        					'name' => 'Kota Pangkal Pinang',
									'code' => '19.71',
									'abbreviation' => 'PGP',
									'license_plate' => 'BN',
	        					],
	        				],
	        			],
						[
							'name' => 'Kepulauan Riau',
							'code' => '21',
	        				'abbreviation' => 'Kp. Riau',
	        				'regencies' => [
	        					[
		        					'name' => 'Kabupaten Bintan',
									'code' => '21.01',
									'abbreviation' => 'BSB',
									'license_plate' => 'BP',
	        					],
	        					[
		        					'name' => 'Kabupaten Karimun',
									'code' => '21.02',
									'abbreviation' => 'TBK',
									'license_plate' => 'BP',
	        					],
	        					[
		        					'name' => 'Kabupaten Kepulauan Anambas',
									'code' => '21.05',
									'abbreviation' => 'TRP',
									'license_plate' => 'BP',
	        					],
	        					[
		        					'name' => 'Kabupaten Lingga',
									'code' => '21.04',
									'abbreviation' => 'DKL',
									'license_plate' => 'BP',
	        					],
	        					[
		        					'name' => 'Kabupaten Natuna',
									'code' => '21.03',
									'abbreviation' => 'RAN',
									'license_plate' => 'BP',
	        					],
	        					[
		        					'name' => 'Kota Batam',
									'code' => '21.71',
									'abbreviation' => 'BTM',
									'license_plate' => 'BP',
	        					],
	        					[
		        					'name' => 'Kota Tanjung Pinang',
									'code' => '21.72',
									'abbreviation' => 'TPG',
									'license_plate' => 'BP',
	        					],
	        				],
	        			],
						[
							'name' => 'Lampung',
							'code' => '18',
	        				'abbreviation' => 'Lampung',
	        				'regencies' => [
	        					[
		        					'name' => 'Kabupaten Lampung Barat',
									'code' => '18.04',
									'abbreviation' => 'LIW',
									'license_plate' => 'BE',
	        					],
								[
		        					'name' => 'Kabupaten Lampung Selatan',
									'code' => '18.01',
									'abbreviation' => 'KLA',
									'license_plate' => 'BE',
	        					],
								[
		        					'name' => 'Kabupaten Lampung Tengah',
									'code' => '18.02',
									'abbreviation' => 'GNS',
									'license_plate' => 'BE',
	        					],
								[
		        					'name' => 'Kabupaten Lampung Timur',
									'code' => '18.07',
									'abbreviation' => 'SDN',
									'license_plate' => 'BE',
	        					],
								[
		        					'name' => 'Kabupaten Lampung Utara',
									'code' => '18.03',
									'abbreviation' => 'KTB',
									'license_plate' => 'BE',
	        					],
								[
		        					'name' => 'Kabupaten Mesuji',
									'code' => '18.11',
									'abbreviation' => 'MSJ',
									'license_plate' => 'BE',
	        					],
								[
		        					'name' => 'Kabupaten Pesawaran',
									'code' => '18.09',
									'abbreviation' => 'GDT',
									'license_plate' => 'BE',
	        					],
								[
		        					'name' => 'Kabupaten Pesisir Barat',
									'code' => '18.13',
									'abbreviation' => 'KRU',
									'license_plate' => 'BE',
	        					],
								[
		        					'name' => 'Kabupaten Pringsewu',
									'code' => '18.10',
									'abbreviation' => 'PRW',
									'license_plate' => 'BE',
	        					],
								[
		        					'name' => 'Kabupaten Tanggamus',
									'code' => '18.06',
									'abbreviation' => 'KOT',
									'license_plate' => 'BE',
	        					],
								[
		        					'name' => 'Kabupaten Tulang Bawang Barat',
									'code' => '18.12',
									'abbreviation' => 'TWG',
									'license_plate' => 'BE',
	        					],
								[
		        					'name' => 'Kabupaten Tulangbawang',
									'code' => '18.05',
									'abbreviation' => 'MGL',
									'license_plate' => 'BE',
	        					],
								[
		        					'name' => 'Kabupaten Way Kanan',
									'code' => '18.08',
									'abbreviation' => 'BBU',
									'license_plate' => 'BE',
	        					],
								[
		        					'name' => 'Kota Bandar Lampung',
									'code' => '18.71',
									'abbreviation' => 'BDL',
									'license_plate' => 'BE',
	        					],
								[
		        					'name' => 'Kota Metro',
									'code' => '18.72',
									'abbreviation' => 'MET',
									'license_plate' => 'BE',
	        					],
	        				],
	        			],
						[
							'name' => 'Riau',
							'code' => '14',
	        				'abbreviation' => 'Riau',
	        				'regencies' => [
	        					[
		        					'name' => 'Kabupaten Bengkalis',
									'code' => '14.03',
									'abbreviation' => 'BLS',
									'license_plate' => 'BM',
	        					],
								[
		        					'name' => 'Kabupaten Indragiri Hilir',
									'code' => '14.04',
									'abbreviation' => 'TBH',
									'license_plate' => 'BM',
	        					],
								[
		        					'name' => 'Kabupaten Indragiri Hulu',
									'code' => '14.02',
									'abbreviation' => 'RGT',
									'license_plate' => 'BM',
	        					],
								[
		        					'name' => 'Kabupaten Kampar',
									'code' => '14.01',
									'abbreviation' => 'BKN',
									'license_plate' => 'BM',
	        					],
								[
		        					'name' => 'Kabupaten Kepulauan Meranti',
									'code' => '14.10',
									'abbreviation' => 'TTG',
									'license_plate' => 'BM',
	        					],
								[
		        					'name' => 'Kabupaten Kuantan Singingi',
									'code' => '14.09',
									'abbreviation' => 'TLK',
									'license_plate' => 'BM',
	        					],
								[
		        					'name' => 'Kabupaten Pelalawan',
									'code' => '14.05',
									'abbreviation' => 'PKK',
									'license_plate' => 'BM',
	        					],
								[
		        					'name' => 'Kabupaten Rokan Hilir',
									'code' => '14.07',
									'abbreviation' => 'UJT',
									'license_plate' => 'BM',
	        					],
								[
		        					'name' => 'Kabupaten Rokan Hulu',
									'code' => '14.06',
									'abbreviation' => 'PRP',
									'license_plate' => 'BM',
	        					],
								[
		        					'name' => 'Kabupaten Siak',
									'code' => '14.08',
									'abbreviation' => 'SAK',
									'license_plate' => 'BM',
	        					],
								[
		        					'name' => 'Kota Dumai',
									'code' => '14.72',
									'abbreviation' => 'DUM',
									'license_plate' => 'BM',
	        					],
								[
		        					'name' => 'Kota Pekanbaru',
									'code' => '14.71',
									'abbreviation' => 'PBR',
									'license_plate' => 'BM',
	        					],
	        				],
	        			],
						[
							'name' => 'Sumatera Barat',
							'code' => '13',
	        				'abbreviation' => 'Sumbar',
	        				'regencies' => [
	        					[
		        					'name' => 'Kabupaten Agam',
									'code' => '13.06',
									'abbreviation' => 'LBB',
									'license_plate' => 'BA',
	        					],
								[
		        					'name' => 'Kabupaten Dharmasraya',
									'code' => '13.10',
									'abbreviation' => 'PLJ',
									'license_plate' => 'BA',
	        					],
								[
		        					'name' => 'Kabupaten Kepulauan Mentawai',
									'code' => '13.09',
									'abbreviation' => 'TPT',
									'license_plate' => 'BA',
	        					],
								[
		        					'name' => 'Kabupaten Lima Puluh Kota',
									'code' => '13.07',
									'abbreviation' => 'SRK',
									'license_plate' => 'BA',
	        					],
								[
		        					'name' => 'Kabupaten Padang Pariaman',
									'code' => '13.05',
									'abbreviation' => 'NPM',
									'license_plate' => 'BA',
	        					],
								[
		        					'name' => 'Kabupaten Pasaman',
									'code' => '13.08',
									'abbreviation' => 'LBS',
									'license_plate' => 'BA',
	        					],
								[
		        					'name' => 'Kabupaten Pasaman Barat',
									'code' => '13.12',
									'abbreviation' => 'SPE',
									'license_plate' => 'BA',
	        					],
								[
		        					'name' => 'Kabupaten Pesisir Selatan',
									'code' => '13.01',
									'abbreviation' => 'PNN',
									'license_plate' => 'BA',
	        					],
								[
		        					'name' => 'Kabupaten Sijunjung',
									'code' => '13.03',
									'abbreviation' => 'MRJ',
									'license_plate' => 'BA',
	        					],
								[
		        					'name' => 'Kabupaten Solok',
									'code' => '13.02',
									'abbreviation' => 'ARS',
									'license_plate' => 'BA',
	        					],
								[
		        					'name' => 'Kabupaten Solok Selatan',
									'code' => '13.11',
									'abbreviation' => 'PDA',
									'license_plate' => 'BA',
	        					],
								[
		        					'name' => 'Kabupaten Tanah Datar',
									'code' => '13.04',
									'abbreviation' => 'BSK',
									'license_plate' => 'BA',
	        					],
								[
		        					'name' => 'Kota Bukittinggi',
									'code' => '13.75',
									'abbreviation' => 'BKT',
									'license_plate' => 'BA',
	        					],
								[
		        					'name' => 'Kota Padang',
									'code' => '13.71',
									'abbreviation' => 'PAD',
									'license_plate' => 'BA',
	        					],
								[
		        					'name' => 'Kota Padang Panjang',
									'code' => '13.74',
									'abbreviation' => 'PDP',
									'license_plate' => 'BA',
	        					],
								[
		        					'name' => 'Kota Pariaman',
									'code' => '13.77',
									'abbreviation' => 'PMN',
									'license_plate' => 'BA',
	        					],
								[
		        					'name' => 'Kota Payakumbuh',
									'code' => '13.76',
									'abbreviation' => 'PYH',
									'license_plate' => 'BA',
	        					],
								[
		        					'name' => 'Kota Sawah Lunto',
									'code' => '13.73',
									'abbreviation' => 'SWL',
									'license_plate' => 'BA',
	        					],
								[
		        					'name' => 'Kota Solok',
									'code' => '13.72',
									'abbreviation' => 'SLK',
									'license_plate' => 'BA',
	        					],
	        				],
	        			],
						[
							'name' => 'Sumatera Selatan',
							'code' => '16',
	        				'abbreviation' => 'Sumsel',
	        				'regencies' => [
	        					[
		        					'name' => 'Kabupaten Banyu Asin',
									'code' => '16.07',
									'abbreviation' => 'PKB',
									'license_plate' => 'BG',
	        					],
								[
		        					'name' => 'Kabupaten Empat Lawang',
									'code' => '16.11',
									'abbreviation' => 'TBG',
									'license_plate' => 'BG',
	        					],
								[
		        					'name' => 'Kabupaten Lahat',
									'code' => '16.04',
									'abbreviation' => 'LHT',
									'license_plate' => 'BG',
	        					],
								[
		        					'name' => 'Kabupaten Muara Enim',
									'code' => '16.03',
									'abbreviation' => 'MRE',
									'license_plate' => 'BG',
	        					],
								[
		        					'name' => 'Kabupaten Musi Banyuasin',
									'code' => '16.06',
									'abbreviation' => 'SKY',
									'license_plate' => 'BG',
	        					],
								[
		        					'name' => 'Kabupaten Musi Rawas',
									'code' => '16.05',
									'abbreviation' => 'MBL',
									'license_plate' => 'BG',
	        					],
								[
		        					'name' => 'Kabupaten Musi Rawas Utara',
									'code' => '16.13',
									'abbreviation' => 'RUP',
									'license_plate' => 'BG',
	        					],
								[
		        					'name' => 'Kabupaten Ogan Ilir',
									'code' => '16.10',
									'abbreviation' => 'IDL',
									'license_plate' => 'BG',
	        					],
								[
		        					'name' => 'Kabupaten Ogan Komering Ilir',
									'code' => '16.02',
									'abbreviation' => 'KAG',
									'license_plate' => 'BG',
	        					],
								[
		        					'name' => 'Kabupaten Ogan Komering Ulu',
									'code' => '16.01',
									'abbreviation' => 'BTA',
									'license_plate' => 'BG',
	        					],
								[
		        					'name' => 'Kabupaten Ogan Komering Ulu Selatan',
									'code' => '16.09',
									'abbreviation' => 'MRD',
									'license_plate' => 'BG',
	        					],
								[
		        					'name' => 'Kabupaten Ogan Komering Ulu Timur',
									'code' => '16.08',
									'abbreviation' => 'MPR',
									'license_plate' => 'BG',
	        					],
								[
		        					'name' => 'Kabupaten Penukal Abab Lematang Ilir',
									'code' => '16.12',
									'abbreviation' => 'TBI',
									'license_plate' => 'BG',
	        					],
								[
		        					'name' => 'Kota Lubuklinggau',
									'code' => '16.73',
									'abbreviation' => 'LLG',
									'license_plate' => 'BG',
	        					],
								[
		        					'name' => 'Kota Pagar Alam',
									'code' => '16.72',
									'abbreviation' => 'PGA',
									'license_plate' => 'BG',
	        					],
								[
		        					'name' => 'Kota Palembang',
									'code' => '16.71',
									'abbreviation' => 'PLG',
									'license_plate' => 'BG',
	        					],
								[
		        					'name' => 'Kota Prabumulih',
									'code' => '16.74',
									'abbreviation' => 'PBM',
									'license_plate' => 'BG',
	        					],
	        				],
	        			],
						[
							'name' => 'Sumatera Utara',
							'code' => '12',
	        				'abbreviation' => 'Sumut',
	        				'regencies' => [
	        					[
		        					'name' => 'Kabupaten Asahan',
									'code' => '12.09',
									'abbreviation' => 'KIS',
									'license_plate' => 'BK',
	        					],
								[
		        					'name' => 'Kabupaten Batu Bara',
									'code' => '12.19',
									'abbreviation' => 'LMP',
									'license_plate' => 'BK',
	        					],
								[
		        					'name' => 'Kabupaten Dairi',
									'code' => '12.11',
									'abbreviation' => 'SDK',
									'license_plate' => 'BB',
	        					],
								[
		        					'name' => 'Kabupaten Deli Serdang',
									'code' => '12.07',
									'abbreviation' => 'LBP',
									'license_plate' => 'BK',
	        					],
								[
		        					'name' => 'Kabupaten Humbang Hasundutan',
									'code' => '12.16',
									'abbreviation' => 'DLS',
									'license_plate' => 'BB',
	        					],
								[
		        					'name' => 'Kabupaten Karo',
									'code' => '12.06',
									'abbreviation' => 'KBJ',
									'license_plate' => 'BK',
	        					],
								[
		        					'name' => 'Kabupaten Labuhan Batu',
									'code' => '12.10',
									'abbreviation' => 'RAP',
									'license_plate' => 'BK',
	        					],
								[
		        					'name' => 'Kabupaten Labuhan Batu Selatan',
									'code' => '12.22',
									'abbreviation' => 'KPI',
									'license_plate' => 'BK',
	        					],
								[
		        					'name' => 'Kabupaten Labuhan Batu Utara',
									'code' => '12.23',
									'abbreviation' => 'AKK',
									'license_plate' => 'BK',
	        					],
								[
		        					'name' => 'Kabupaten Langkat',
									'code' => '12.05',
									'abbreviation' => 'STB',
									'license_plate' => 'BK',
	        					],
								[
		        					'name' => 'Kabupaten Mandailing Natal',
									'code' => '12.13',
									'abbreviation' => 'PYB',
									'license_plate' => 'BB',
	        					],
								[
		        					'name' => 'Kabupaten Nias',
									'code' => '12.04',
									'abbreviation' => 'GST',
									'license_plate' => 'BB',
	        					],
								[
		        					'name' => 'Kabupaten Nias Barat',
									'code' => '12.25',
									'abbreviation' => 'LHM',
									'license_plate' => 'BB',
	        					],
								[
		        					'name' => 'Kabupaten Nias Selatan',
									'code' => '12.14',
									'abbreviation' => 'TLD',
									'license_plate' => 'BB',
	        					],
								[
		        					'name' => 'Kabupaten Nias Utara',
									'code' => '12.24',
									'abbreviation' => 'LTU',
									'license_plate' => 'BB',
	        					],
								[
		        					'name' => 'Kabupaten Padang Lawas',
									'code' => '12.21',
									'abbreviation' => 'SBH',
									'license_plate' => 'BB',
	        					],
								[
		        					'name' => 'Kabupaten Padang Lawas Utara',
									'code' => '12.20',
									'abbreviation' => 'GNT',
									'license_plate' => 'BB',
	        					],
								[
		        					'name' => 'Kabupaten Pakpak Bharat',
									'code' => '12.15',
									'abbreviation' => 'SAL',
									'license_plate' => 'BB',
	        					],
								[
		        					'name' => 'Kabupaten Samosir',
									'code' => '12.17',
									'abbreviation' => 'PRR',
									'license_plate' => 'BB',
	        					],
								[
		        					'name' => 'Kabupaten Serdang Bedagai',
									'code' => '12.18',
									'abbreviation' => 'SRH',
									'license_plate' => 'BK',
	        					],
								[
		        					'name' => 'Kabupaten Simalungun',
									'code' => '12.08',
									'abbreviation' => 'PMS',
									'license_plate' => 'BK',
	        					],
								[
		        					'name' => 'Kabupaten Tapanuli Selatan',
									'code' => '12.03',
									'abbreviation' => 'PSP',
									'license_plate' => 'BB',
	        					],
								[
		        					'name' => 'Kabupaten Tapanuli Tengah',
									'code' => '12.01',
									'abbreviation' => 'SBG',
									'license_plate' => 'BB',
	        					],
								[
		        					'name' => 'Kabupaten Tapanuli Utara',
									'code' => '12.02',
									'abbreviation' => 'TRT',
									'license_plate' => 'BB',
	        					],
								[
		        					'name' => 'Kabupaten Toba Samosir',
									'code' => '12.12',
									'abbreviation' => 'BLG',
									'license_plate' => 'BB',
	        					],
								[
		        					'name' => 'Kota Binjai',
									'code' => '12.75',
									'abbreviation' => 'BNJ',
									'license_plate' => 'BK',
	        					],
								[
		        					'name' => 'Kota Gunungsitoli',
									'code' => '12.78',
									'abbreviation' => 'GST',
									'license_plate' => 'BB',
	        					],
								[
		        					'name' => 'Kota Medan',
									'code' => '12.71',
									'abbreviation' => 'MDN',
									'license_plate' => 'BK',
	        					],
								[
		        					'name' => 'Kota Padangsidimpuan',
									'code' => '12.77',
									'abbreviation' => 'PSP',
									'license_plate' => 'BB',
	        					],
								[
		        					'name' => 'Kota Pematang Siantar',
									'code' => '12.72',
									'abbreviation' => 'PMS',
									'license_plate' => 'BK',
	        					],
								[
		        					'name' => 'Kota Sibolga',
									'code' => '12.73',
									'abbreviation' => 'SBG',
									'license_plate' => 'BB',
	        					],
								[
		        					'name' => 'Kota Tanjung Balai',
									'code' => '12.74',
									'abbreviation' => 'TJB',
									'license_plate' => 'BK',
	        					],
								[
		        					'name' => 'Kota Tebing Tinggi',
									'code' => '12.76',
									'abbreviation' => 'TBT',
									'license_plate' => 'BK'
	        					],
	        				],
	        			],
	        		]
        		],
			],
        ];

		collect($areas)->each(function ($area) {
			$island = \App\Island::firstOrCreate([
				'name' => $area['island']['name'],
				'code' => $area['island']['code'],
			]);
			collect($area['island']['provinces'])->each(function ($provinces) use ($island) {
        		$province = $island->provinces()->firstOrCreate([
					'name' => $provinces['name'],
					'code' => $provinces['code'],
        			'abbreviation' => $provinces['abbreviation'],
				]);
				collect($provinces['regencies'])->each(function ($regency) use ($province) {
					$licensePlate = \App\LicensePlate::firstOrCreate(['name' => $regency['license_plate']]);
        			$province->regencies()->firstOrCreate([
        				'name' => $regency['name'],
						'code' => $regency['code'],
						'abbreviation' => $regency['abbreviation']
        			])->licensePlates()->sync([$licensePlate->id]);
				});
			});
		});
    }
}
